### PR TITLE
Allow to pass a file to the program

### LINKED ISSUE #31: acrordrdc does't provide .desktop file, can't select it to open PDF files from Nautilus
This is a wonderful snap, make it very easy to get Adobe Reader working in Ubuntu.

I note that I had problems with running it the second time, for which the following was helpful:
https://linuxconfig.org/how-to-install-adobe-acrobat-reader-dc-wine-on-ubuntu-20-04-focal-fossa-linux

However, I wanted to note that I cannot associate acrordrdc with .pdf files because this snap does not include a .desktop file. Having this would improve usability, since one could right-click a PDF and select to open it with acrordrdc instead of default Evince.

Not sure how Snaps handle the installation/use of .desktop files. This seems to be relevant though:
https://snapcraft.io/docs/desktop-menu-icon-support

### PR DESCRIPTION
**Pull request by DefaultX-od**
fixes #31

### CODE REVIEW

**Comment by mmtrt** [comment]
Tested?

**Comment by DefaultX-od** [comment]
Yes, works like a charm!

**Comment by mmtrt** [comment]
LGTM then.

**Comment by DefaultX-od** [comment]
If the program is already opened, it will show an error and will not open the file, but it is a [known issue](https://community.adobe.com/t5/acrobat-discussions/i-have-been-getting-the-quot-acrobat-fail-to-send-a-dde-command-quot/td-p/8181904) and is not related to the changes I've made.

**Pull request merged**
